### ISSUE TITLE
The OMDb API has gone private

### ISSUE THREAD

**Issue by VasilyShelkov** [arunoda/learnnextjs-content#16]
[Fetching Batman Movies](https://learnnextjs.com/basics/fetching-data-for-pages/fetching-batman-movies) is not possible to use for [free from OMDb anymore](https://www.patreon.com/posts/api-is-going-10743518). For the lesson I have instead used a different unauthenticated public API that I picked from [this list](https://github.com/toddmotto/public-apis#anime).

I'd like to suggest updating the lessons to use a different API. Take your pick and I'm happy to make a PR :) I personally decided to use this [Studio Ghibli api](https://ghibliapi.herokuapp.com/)

P.S. great tutorials

**Comment by arunoda** [comment]
Oh!
@VasilyShelkov thanks. Let's go with that API.
I like anything that works.
Send me a PR 🙏

**Comment by VasilyShelkov** [comment]
Sent a PR https://github.com/arunoda/learnnextjs-content/pull/22

Hopefully it's ok

**Comment by arunoda** [comment]
Thanks.
Fixed with #21
