### ISSUE TITLE
Using a Markdown component that wasn't previously introduced

### ISSUE THREAD

**Issue by Yuri-M-Dias** [arunoda/learnnextjs-content#17]
On lesson 8 "Styling Components", in the "Global Styles" section, the code uses a "Markdown" component that wasn't introduced in any previous lessons, nor gives the code for it.

**Comment by arunoda** [comment]
If you follow [this setup guide](https://learnnextjs.com/basics/styling-components/setup), markdown component will be there.

Anyway, our focus is not to teach styling not exactly about creating a Markdown component.
