### ISSUE TITLE
Cannot read property 'getInitialProps' of undefined

### ISSUE THREAD

**Issue by spences10** [arunoda/learnnextjs-content#24]
Hi there, going through the example pages and on: https://learnnextjs.com/basics/getting-started/first-page I get the following:

![image](https://cloud.githubusercontent.com/assets/234708/26482608/39de389a-41e0-11e7-9f8a-3c72b39440ba.png)

Let me know if you need anything else

**Comment by arunoda** [comment]
For now simple reload the page. We fixed this bug.
Basically this happens when your page doesn't have a default export.

**Comment by spences10** [comment]
Thanks
