### ISSUE TITLE
9-deploying-a-nextjs-app.js

### ISSUE THREAD

**Issue by abflett** [arunoda/learnnextjs-content#33]
For me port 80 does not work for me but **443** does, assumed 443 because HTTPS. Port 80 used for questions and that may not apply for all. :dango:

**Comment by arunoda** [comment]
Yes. True. We need to edit that.

**Comment by arunoda** [comment]
Changed to this.
<img width="618" alt="screen shot 2017-07-15 at 2 55 34 am" src="https://user-images.githubusercontent.com/50838/28231435-1ebe2066-6909-11e7-8f7b-327048b70f34.png">
