### ISSUE TITLE
Header.js not referenced correctly

### ISSUE THREAD

**Issue by artingei** [arunoda/learnnextjs-content#4]
https://github.com/arunoda/learnnextjs-content/blob/master/content/1-basics/3-using-shared-components.js#L93

Header.js should be referenced '../components/Header.js'

**Comment by arunoda** [comment]
Do you find any issues? We don't need to add `.js`. 
Or is it something else?

**Comment by arunoda** [comment]
Closing since inactive. Need more info to reproduce.
