### ISSUE TITLE
Is next/link really a higher order component?

### ISSUE THREAD

**Issue by knpwrs** [arunoda/learnnextjs-content#45]
I'm currently going through [learnnextjs.com](https://learnnextjs.com/). [This page](https://learnnextjs.com/basics/navigate-between-pages/hoc) says the following:

> ## Link is Just a Higher Order Component (HOC)
> Actually, the style prop on `next/link` has no effect. That's because next/link is just a [higher order component][hoc] which only accepts the "href" and some similar props. If you need to style it, you need to do it to the underlying component.

This confused me because `next/link` isn't used like a higher order component, it's used like a component that can wrap children. The [linked documentation page][hoc] has the actual definition of higher order component:

> Concretely, **a higher-order component is a function that takes a component and returns a new component.**

That page also says:

> An HOC is a pure function with zero side-effects.

and

> Don't Use HOCs Inside the render Method.

So you don't directly use HOCs in JSX, and they don't directly accept props because they are just functions which return components. I don't see any references on that page to the style of component that `next/link` is. The terminology is important here because the idea behind higher order components is that they can be functionally composed. This isn't true for `next/link`. Concretely, the following does not work:

```js
import { compose, pure } from 'recompose';
import Link from 'next/link';

compose(
  pure,
  Link,
)(() => <a>About</a>);
```

You will actually see an error: `Cannot call a class as a function.`

Am I wrong? My understanding is that Higher Order Components are named after [Higher Order Functions](https://en.wikipedia.org/wiki/Higher-order_function). If `next/link` were actually a higher order component I'd expect it to expose an API like such:

```js
link({ href: '/about' })(() => <a>About</a>);
```

That will work with functional composition and also has a functional interface for supply the `href` "prop."

Anyway, that's just a really roundabout way of saying that I believe `next/link` is just a component, and not a higher order component.

[hoc]: https://facebook.github.io/react/docs/higher-order-components.html

**Comment by arunoda** [comment]
You are correct.
I've change the wording.
See: https://learnnextjs.com/basics/navigate-between-pages/wrapper-component

<img width="639" alt="screen shot 2017-09-14 at 4 38 54 am" src="https://user-images.githubusercontent.com/50838/30404921-acd89e94-9906-11e7-9918-347313c27c30.png">
