### ISSUE TITLE
Error on Lazy loading component section

### ISSUE THREAD

**Issue by kurapikats** [arunoda/learnnextjs-content#63]
The page loads for a moment then this error shows:
`Cannot read property 'querySelectorAll' of null`

**URL:**
https://learnnextjs.com/excel/lazy-loading-components/hello-dynamic-components

**Screencast:**
http://nimb.ws/OWrvSj

**Comment by wonderchang** [comment]
+1

The error occurs just because `react-highlight` hasn't supported React v16+ yet. To workaround this, see https://github.com/akiran/react-highlight/issues/39#issuecomment-334898100.

**Comment by arzafran** [comment]
hey, I've found a solution for your issue, the thing is that `react-highlight` hasn't been updated to support `react@16.2.0` someone made a patch, and his build is working but it's not merged yet.
So Imma call this a workaround based on a workaround, simply change the react highlight version in your `package.json` to `briancappello/react-highlight#react-v16-compiled` and `npm install`

your package.json should look like this:

```json
{
  "name": "hello-next",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "analyze": "cross-env ANALYZE=1 next build"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cross-env": "^5.0.1",
    "marked": "^0.3.6",
    "next": "^4.2.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-highlight": "briancappello/react-highlight#react-v16-compiled",
    "webpack-bundle-analyzer": "^2.8.3"
  }
}
```

**Comment by timneutkens** [comment]
https://github.com/arunoda/learnnextjs-demo/pull/35
