### ISSUE TITLE
Lazy Loading Components error - Cannot read property 'querySelectorAll'

### ISSUE THREAD

**Issue by manu-codes** [arunoda/learnnextjs-content#75]
How to reproduce 

1.  [setup the project](https://learnnextjs.com/excel/lazy-loading-components/setup)
2. Do till `npm run dev`
3. go to link - http://localhost:3000/
4. Navigate to [Hello Next.js](http://localhost:3000/p/hello-nextjs)

After all the steps above getting an error - **Cannot read property 'querySelectorAll' of null**

![nextjsissue](https://user-images.githubusercontent.com/2102862/35510642-f283e794-051e-11e8-9f16-ac463a9dc48e.png)

Not sure version problem with any of the npm modules that i have used. My dependencies look like 

` "dependencies": {
    "cross-env": "^5.0.1",
    "marked": "^0.3.6",
    "next": "^4.2.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-highlight": "^0.10.0",
    "webpack-bundle-analyzer": "^2.8.3"
  }`

**Comment by arzafran** [comment]
hey, I've found a solution for your issue, the thing is that `react-highlight` hasn't been updated to support `react@16.2.0` someone made a patch, and his build is working but it's not merged yet.
So Imma call this a workaround based on a workaround, simply change the react highlight version in your `package.json` to `briancappello/react-highlight#react-v16-compiled` and `npm install`

your package.json should look like this:

```json
{
  "name": "hello-next",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "analyze": "cross-env ANALYZE=1 next build"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cross-env": "^5.0.1",
    "marked": "^0.3.6",
    "next": "^4.2.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-highlight": "briancappello/react-highlight#react-v16-compiled",
    "webpack-bundle-analyzer": "^2.8.3"
  }
}
```

**Comment by timneutkens** [comment]
https://github.com/arunoda/learnnextjs-demo/pull/35
